const Numbers0_50 = {
    name: 'Numbers 0-50',
    flashcards: [
      {
        id: 1,
        englishImage: 'https://cdn3.iconfinder.com/data/icons/letters-and-numbers-1/32/number_0_blue-512.png',
        french: 'Zéro',
        phonetic: 'zeʁo',
      },
      {
        id: 2,
        englishImage: 'https://www.freepnglogos.com/uploads/1-number-png/cartoon-1-number-five-for-friday-time-beach-sand-3.png',
        french: 'Un',
        phonetic: 'œ̃',
      },
      {
        id: 3,
        englishImage: '',
        french: 'Deux',
        phonetic: 'dø',
      },
      {
        id: 4,
        englishImage: 'https://www.pngall.com/wp-content/uploads/2/3-Number-PNG.png',
        french: 'Trois',
        phonetic: 'tʁwa',
      },
      {
        id: 5,
        englishImage: '',
        french: 'Quatre',
        phonetic: 'katʁ',
      },
      {
        id: 6,
        englishImage: '',
        french: 'Cinq',
        phonetic: 'sɛ̃k',
      },
      {
        id: 7,
        englishImage: '',
        french: 'Six',
        phonetic: 'sis',
      },
      {
        id: 8,
        englishImage: '',
        french: 'Sept',
        phonetic: 'sɛt',
      },
      {
        id: 9,
        englishImage: '',
        french: 'Huit',
        phonetic: 'ɥit',
      },
      {
        id: 10,
        englishImage: '',
        french: 'Neuf',
        phonetic: 'nœf',
      },
      {
        id: 11,
        englishImage: '',
        french: 'Dix',
        phonetic: 'dis',
      },
      {
        id: 12,
        englishImage: '',
        french: 'Onze',
        phonetic: 'ɔ̃z',
      },
      {
        id: 13,
        englishImage: '',
        french: 'Douze',
        phonetic: 'duz',
      },
      {
        id: 14,
        englishImage: '',
        french: 'Treize',
        phonetic: 'tʁɛz',
      },
      {
        id: 15,
        englishImage: '',
        french: 'Quatorze',
        phonetic: 'katɔʁz',
      },
      {
        id: 16,
        englishImage: '',
        french: 'Quinze',
        phonetic: 'kɛ̃z',
      },
      {
        id: 17,
        englishImage: '',
        french: 'Seize',
        phonetic: 'sɛz',
      },
      {
        id: 18,
        englishImage: '',
        french: 'Dix-sept',
        phonetic: 'dis sɛt',
      },
      {
        id: 19,
        englishImage: '',
        french: 'Dix-huit',
        phonetic: 'dis ɥit',
      },
      {
        id: 20,
        englishImage: '',
        french: 'Dix-neuf',
        phonetic: 'dis nœf',
      },
      {
        id: 21,
        englishImage: '',
        french: 'Vingt',
        phonetic: 'vɛ̃',
      },
      {
        id: 22,
        englishImage: '',
        french: 'Vingt et un',
        phonetic: 'vɛ̃t e œ̃',
      },
      {
        id: 23,
        englishImage: '',
        french: 'Vingt-deux',
        phonetic: 'vɛ̃t dø',
      },
      {
        id: 24,
        englishImage: '',
        french: 'Vingt-trois',
        phonetic: 'vɛ̃t tʁwa',
      },
      {
        id: 25,
        englishImage: '',
        french: 'Vingt-quatre',
        phonetic: 'vɛ̃t katʁ',
      },
      {
        id: 26,
        englishImage: '',
        french: 'Vingt-cinq',
        phonetic: 'vɛ̃ sɛ̃k',
      },
      {
        id: 27,
        englishImage: '',
        french: 'Vingt-six',
        phonetic: 'vɛ̃ sis',
      },
      {
        id: 28,
        englishImage: '',
        french: 'Vingt-sept',
        phonetic: 'vɛ̃ sɛt',
      },
      {
        id: 29,
        englishImage: '',
        french: 'Vingt-huit',
        phonetic: 'vɛ̃ ɥit',
      },
      {
        id: 30,
        englishImage: '',
        french: 'Vingt-neuf',
        phonetic: 'vɛ̃ nœf',
      },
      {
        id: 31,
        englishImage: '',
        french: 'Trente',
        phonetic: 'tʁɑ̃t',
      },
      {
        id: 32,
        englishImage: '',
        french: 'Trente et un',
        phonetic: 'tʁɑ̃t e œ̃',
      },
      {
        id: 33,
        englishImage: '',
        french: 'Trente-deux',
        phonetic: 'tʁɑ̃t dø',
      },
      {
        id: 34,
        englishImage: '',
        french: 'Trente-trois',
        phonetic: 'tʁɑ̃t tʁwa',
      },
      {
        id: 35,
        englishImage: '',
        french: 'Trente-quatre',
        phonetic: 'tʁɑ̃t katʁ',
      },
      {
        id: 36,
        englishImage: '',
        french: 'Trente-cinq',
        phonetic: 'tʁɑ̃ sɛ̃k',
      },
      {
        id: 37,
        englishImage: '',
        french: 'Trente-six',
        phonetic: 'tʁɑ̃ sis',
      },
      {
        id: 38,
        englishImage: '',
        french: 'Trente-sept',
        phonetic: 'tʁɑ̃ sɛt',
      },
      {
        id: 39,
        englishImage: '',
        french: 'Trente-huit',
        phonetic: 'tʁɑ̃ ɥit',
      },
      {
        id: 40,
        englishImage: '',
        french: 'Trente-neuf',
        phonetic: 'tʁɑ̃ nœf',
      },
      {
        id: 41,
        englishImage: '',
        french: 'Quarante',
        phonetic: 'kaʁɑ̃t',
      },
      {
        id: 42,
        englishImage: '',
        french: 'Quarante et un',
        phonetic: 'kaʁɑ̃t e œ̃',
      },
      {
        id: 43,
        englishImage: '',
        french: 'Quarante-deux',
        phonetic: 'kaʁɑ̃t dø',
      },
      {
        id: 44,
        englishImage: '',
        french: 'Quarante-trois',
        phonetic: 'kaʁɑ̃t tʁwa',
      },
      {
        id: 45,
        englishImage: '',
        french: 'Quarante-quatre',
        phonetic: 'kaʁɑ̃t katʁ',
      },
      {
        id: 46,
        englishImage: '',
        french: 'Quarante-cinq',
        phonetic: 'kaʁɑ̃ sɛ̃k',
      },
      {
        id: 47,
        englishImage: '',
        french: 'Quarante-six',
        phonetic: 'kaʁɑ̃ sis',
      },
      {
        id: 48,
        englishImage: '',
        french: 'Quarante-sept',
        phonetic: 'kaʁɑ̃ sɛt',
      },
      {
        id: 49,
        englishImage: '',
        french: 'Quarante-huit',
        phonetic: 'kaʁɑ̃ ɥit',
      },
      {
        id: 50,
        englishImage: '',
        french: 'Quarante-neuf',
        phonetic: 'kaʁɑ̃ nœf',
      },
    ],
  };
  
  export default Numbers0_50;
  