const Numbers0_50 = {
    name: 'Numbers 0-50',
    flashcards: [
      {
        id: 1,
        englishImage: 'https://cdn3.iconfinder.com/data/icons/letters-and-numbers-1/32/number_0_blue-512.png',
        french: 'Zéro',
        phonetic: 'zeʁo',
      },
      {
        id: 2,
        englishImage: 'https://www.freepnglogos.com/uploads/1-number-png/cartoon-1-number-five-for-friday-time-beach-sand-3.png',
        french: 'Un',
        phonetic: 'œ̃',
      },
      {
        id: 3,
        englishImage: 'https://gallery.yopriceville.com/var/albums/Free-Clipart-Pictures/Decorative-Numbers/Cute_Number_Two_PNG_Clipart_Image.png?m=1437447301',
        french: 'Deux',
        phonetic: 'dø',
      },
      {
        id: 4,
        englishImage: 'https://www.pngall.com/wp-content/uploads/2/3-Number-PNG.png',
        french: 'Trois',
        phonetic: 'tʁwa',
      },
      {
        id: 5,
        englishImage: 'https://cdn.pixabay.com/photo/2021/03/05/19/20/numbers-6072127_1280.png',
        french: 'Quatre',
        phonetic: 'katʁ',
      },
      {
        id: 6,
        englishImage: 'https://www.freepnglogos.com/uploads/number-5-png/number-5-animal-number-education-animal-numbers-animal-number-0.png',
        french: 'Cinq',
        phonetic: 'sɛ̃k',
      },
      {
        id: 7,
        englishImage: 'https://www.pngplay.com/wp-content/uploads/1/6-Number-PNG-HD-Free-Image.png',
        french: 'Six',
        phonetic: 'sis',
      },
      {
        id: 8,
        englishImage: 'https://i.pinimg.com/originals/a4/51/8a/a4518aa4842a0d83761aec10cfc7bd55.png',
        french: 'Sept',
        phonetic: 'sɛt',
      },
      {
        id: 9,
        englishImage: 'https://images.vexels.com/media/users/3/303035/isolated/preview/ccc64294c90edee8a30d7a7b5a8f5d4f-animal-kawaii-alphabet-8-number.png',
        french: 'Huit',
        phonetic: 'ɥit',
      },
      {
        id: 10,
        englishImage: 'https://png.pngtree.com/png-clipart/20220716/ourmid/pngtree-cute-number-nine-png-image_5983243.png',
        french: 'Neuf',
        phonetic: 'nœf',
      },
      {
        id: 11,
        englishImage: 'https://png.pngtree.com/png-vector/20220613/ourmid/pngtree-cute-pink-number-ten-png-image_5060477.png',
        french: 'Dix',
        phonetic: 'dis',
      },
      {
        id: 12,
        englishImage: 'https://png.pngtree.com/png-clipart/20230803/original/pngtree-number-eleven-and-11-toys-digit-book-game-vector-picture-image_9344484.png',
        french: 'Onze',
        phonetic: 'ɔ̃z',
      },
      {
        id: 13,
        englishImage: 'https://digitallibrary.io/wp-content/uploads/h5p/content/820/images/file-61839937252fb.png',
        french: 'Douze',
        phonetic: 'duz',
      },
      {
        id: 14,
        englishImage: 'https://media.baamboozle.com/uploads/images/485766/1632123946_18026_url.png',
        french: 'Treize',
        phonetic: 'tʁɛz',
      },
      {
        id: 15,
        englishImage: 'https://static.vecteezy.com/system/resources/thumbnails/019/552/752/small/number-14-design-in-3d-render-png.png',
        french: 'Quatorze',
        phonetic: 'katɔʁz',
      },
      {
        id: 16,
        englishImage: 'https://digitallibrary.io/wp-content/uploads/h5p/content/9402/images/image-6227146ea864f.png',
        french: 'Quinze',
        phonetic: 'kɛ̃z',
      },
      {
        id: 17,
        englishImage: 'https://hypixel.net/attachments/16-png.942951/',
        french: 'Seize',
        phonetic: 'sɛz',
      },
      {
        id: 18,
        englishImage: 'https://digitallibrary.io/wp-content/uploads/h5p/content/820/images/file-618398d7f21e1.png',
        french: 'Dix-sept',
        phonetic: 'dis sɛt',
      },
      {
        id: 19,
        englishImage: 'https://www.pngmart.com/files/23/18th-PNG-Isolated-Photo.png',
        french: 'Dix-huit',
        phonetic: 'dis ɥit',
      },
      {
        id: 20,
        englishImage: 'https://cdn-icons-png.flaticon.com/512/6287/6287080.png',
        french: 'Dix-neuf',
        phonetic: 'dis nœf',
      },
      {
        id: 21,
        englishImage: 'https://www.pngmart.com/files/23/20-PNG-Pic.png',
        french: 'Vingt',
        phonetic: 'vɛ̃',
      },
      {
        id: 22,
        englishImage: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Frankfurt_am_Main_Tram_21.png',
        french: 'Vingt et un',
        phonetic: 'vɛ̃t e œ̃',
      },
      {
        id: 23,
        englishImage: 'https://www.pngkit.com/png/full/29-296990_png-globos-22-numero-sticker-fiesta-party-happybirthday.png',
        french: 'Vingt-deux',
        phonetic: 'vɛ̃t dø',
      },
      {
        id: 24,
        englishImage: 'https://images.squarespace-cdn.com/content/v1/5e62e59ec769704b155a692f/117a8ae5-43d2-4920-9353-e96bad7a2d84/GMS+Racing+%2323.png',
        french: 'Vingt-trois',
        phonetic: 'vɛ̃t tʁwa',
      },
      {
        id: 25,
        englishImage: 'https://static.vecteezy.com/system/resources/thumbnails/011/297/934/small_2x/24-years-anniversary-number-png.png',
        french: 'Vingt-quatre',
        phonetic: 'vɛ̃t katʁ',
      },
      {
        id: 26,
        englishImage: 'https://assets.stickpng.com/images/5a2aeecbdb68181c8f184dc3.png',
        french: 'Vingt-cinq',
        phonetic: 'vɛ̃ sɛ̃k',
      },
      {
        id: 27,
        englishImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/RO_Roadsign_26.svg/2048px-RO_Roadsign_26.svg.png',
        french: 'Vingt-six',
        phonetic: 'vɛ̃ sis',
      },
      {
        id: 28,
        englishImage: 'https://static.vecteezy.com/system/resources/thumbnails/022/892/273/small/3d-illustration-of-red-number-27-or-twenty-seven-inner-shadow-png.png',
        french: 'Vingt-sept',
        phonetic: 'vɛ̃ sɛt',
      },
      {
        id: 29,
        englishImage: 'https://images.vexels.com/media/users/3/126942/isolated/preview/284e2d8612da429d5af6b15f82e02146-28th-day-calendar-icon.png',
        french: 'Vingt-huit',
        phonetic: 'vɛ̃ ɥit',
      },
      {
        id: 30,
        englishImage: 'https://static.vecteezy.com/system/resources/previews/011/016/779/non_2x/mental-yellow-color-29-3d-number-free-png.png',
        french: 'Vingt-neuf',
        phonetic: 'vɛ̃ nœf',
      },
      {
        id: 31,
        englishImage: 'https://static.vecteezy.com/system/resources/previews/020/967/146/original/cute-minimal-calendar-day-30-illustration-sticker-template-decorated-png.png',
        french: 'Trente',
        phonetic: 'tʁɑ̃t',
      },
      {
        id: 32,
        englishImage: 'https://cdn-icons-png.flaticon.com/512/6287/6287000.png',
        french: 'Trente et un',
        phonetic: 'tʁɑ̃t e œ̃',
      },
      {
        id: 33,
        englishImage: 'https://www.gran-turismo.com/gtsport/decal/7422574300900656144_1.png',
        french: 'Trente-deux',
        phonetic: 'tʁɑ̃t dø',
      },
      {
        id: 34,
        englishImage: 'https://static.vecteezy.com/system/resources/previews/011/297/524/original/33-years-anniversary-number-png.png',
        french: 'Trente-trois',
        phonetic: 'tʁɑ̃t tʁwa',
      },
      {
        id: 35,
        englishImage: 'https://jersey34tennis.com/wp-content/uploads/2021/07/34.png',
        french: 'Trente-quatre',
        phonetic: 'tʁɑ̃t katʁ',
      },
      {
        id: 36,
        englishImage: 'https://static.vecteezy.com/system/resources/previews/011/016/810/original/mental-yellow-color-35-3d-number-free-png.png',
        french: 'Trente-cinq',
        phonetic: 'tʁɑ̃ sɛ̃k',
      },
      {
        id: 37,
        englishImage: 'https://4.bp.blogspot.com/_MWz5rMNRrCo/TFaVEEqH4rI/AAAAAAAAAL4/DVhOEM-J5X0/s1600/Number_36_600x600_pixels.png',
        french: 'Trente-six',
        phonetic: 'tʁɑ̃ sis',
      },
      {
        id: 38,
        englishImage: 'https://www.spainspectors.com/pub/static/frontend/New-theme/new-theme/en_US/images/numbers/37.png',
        french: 'Trente-sept',
        phonetic: 'tʁɑ̃ sɛt',
      },
      {
        id: 39,
        englishImage: 'https://cdn-icons-png.flaticon.com/512/9928/9928993.png',
        french: 'Trente-huit',
        phonetic: 'tʁɑ̃ ɥit',
      },
      {
        id: 40,
        englishImage: 'https://nathanscott85.github.io/Blog/assets/img/39.png',
        french: 'Trente-neuf',
        phonetic: 'tʁɑ̃ nœf',
      },
      {
        id: 41,
        englishImage: 'https://static.vecteezy.com/system/resources/previews/011/287/811/original/number-40-3d-png.png',
        french: 'Quarante',
        phonetic: 'kaʁɑ̃t',
      },
      {
        id: 42,
        englishImage: 'https://static.vecteezy.com/system/resources/thumbnails/019/552/875/small/number-41-design-in-3d-render-png.png',
        french: 'Quarante et un',
        phonetic: 'kaʁɑ̃t e œ̃',
      },
      {
        id: 43,
        englishImage: 'https://skeletalabstractcom.files.wordpress.com/2019/01/42.png',
        french: 'Quarante-deux',
        phonetic: 'kaʁɑ̃t dø',
      },
      {
        id: 44,
        englishImage: 'https://www.gran-turismo.com/gtsport/decal/7431591464344257552_1.png',
        french: 'Quarante-trois',
        phonetic: 'kaʁɑ̃t tʁwa',
      },
      {
        id: 45,
        englishImage: 'https://static.vecteezy.com/system/resources/previews/024/652/388/original/44-number-balloon-pink-png.png',
        french: 'Quarante-quatre',
        phonetic: 'kaʁɑ̃t katʁ',
      },
      {
        id: 46,
        englishImage: 'https://www.gran-turismo.com/gtsport/decal/8215150675610338320_1.png',
        french: 'Quarante-cinq',
        phonetic: 'kaʁɑ̃ sɛ̃k',
      },
      {
        id: 47,
        englishImage: 'https://seeklogo.com/images/1/46-magazine-logo-A511E7595D-seeklogo.com.png',
        french: 'Quarante-six',
        phonetic: 'kaʁɑ̃ sis',
      },
      {
        id: 48,
        englishImage: 'https://static.vecteezy.com/system/resources/previews/011/016/791/original/mental-yellow-color-47-3d-number-free-png.png',
        french: 'Quarante-sept',
        phonetic: 'kaʁɑ̃ sɛt',
      },
      {
        id: 49,
        englishImage: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/GR-EO48t.png',
        french: 'Quarante-huit',
        phonetic: 'kaʁɑ̃ ɥit',
      },
      {
        id: 50,
        englishImage: 'https://seeklogo.com/images/1/49_Ken_Schrader-logo-0FAFB596A6-seeklogo.com.png',
        french: 'Quarante-neuf',
        phonetic: 'kaʁɑ̃ nœf',
      },
      {
        id: 51,
        englishImage: 'https://freepngimg.com/thumb/numbers/129864-50-number-hq-image-free.png',
        french: 'cinquante',
        phonetic: 'sɛ̃kɑ̃t',
      }
    ],
  };
  
  export default Numbers0_50;
  